GET http://localhost:5555/


### Register a new user -- POST /auth/register
POST http://localhost:5555/auth/register
Content-Type: application/json

{
  "username": "chris@chris.com",
  "password": "mypass"
}